IDCODE = "IDCODE"
TYPE = "TYPE"
SRC_ID = "SRC_ID"
DEST_ID = "DEST_ID"
UDPPORT = "UDPPORT"
TCPPORT = "TCPPORT"
DATARATE="DATARATE"
DATAINPUT = "DATAINPUT"
FILENAME = "FILENAME"
PROTOCOL = "PROTOCOL"
PDC_SETUP="PDC_SETUP"

SOURCE_DETAILS = "SOURCE_DETAILS"
DESTINATION_DETAILS = "DESTINATION_DETAILS"

IP="IP"
NAME="NAME"
PASSWD="PASSWD"

# PDC CSV FILE ROW FIELDS
CSV_HEADER = ['iPDC SETUP FIELDS','iPDC ID (integer)','TCP Port (1500-65535)','UDP Port (1500-65535)','iDB Server IP','SOURCE_DEVICES_COUNT',	'DESTINATION_DEVICE_COUNT','WAIT TIME (can be used in future)']
CSV_SOURCE_HEADER=['SOURCE DEVICE FIELDS','DEVICE ID','DEVICE IP','Port  (1500-65535)','PORT TYPE']
CSV_DEST_HEADER = ['DEST DEIVICE FIELDS','DEVICE IP_ADDRESS','PROTOCOL']

NoOfMachines = 'NoOfMachines'
NoOfPMUs = 'NoOfPMUs'
NoOfPMUsOnOneMachine = 'NoOfPMUsOnOneMachine'
COUNT = {NoOfMachines:-1,NoOfPMUs:0,NoOfPMUsOnOneMachine:100}

topology = {IDCODE:[],TYPE:[],SRC_ID:[],DEST_ID:[], UDPPORT:[],TCPPORT:[],DATAINPUT:[],FILENAME:[],DATARATE:[],PROTOCOL:[]}
ipList = {IP:[],NAME:[],PASSWD:[]}
pdcFileNames = {}
IPToIDMapList = {}
PDC_DETAILS = {PDC_SETUP:[],SOURCE_DETAILS:[],DESTINATION_DETAILS:[]}

REMOTE_PMU_PATH = 'WAMS/iPMU/'
REMOTE_PDC_PATH = 'WAMS/iPDC/'
LOCAL_PMU_CSV_PATH = 'data/ipmu/'
LOCAL_PDC_CSV_PATH = 'data/ipdc/'
